models:
  - 81U40056PH
  - 81U40055PH
  - 81UE0057PH
  - 81TD000XPH
  - 81RS002APH
fields:
  - "Model"
  - "Product"
  - "Region"
  - "Country/Region"
  - "Machine Type"
  - "Processor"
  - "Graphics"
  - "Chipset"
  - "Memory"
  - "Storage"
  - "Display"
  - "Touchscreen"
  - "Pen"
  - "Optical"
  - "Media Reader"
  - "Ethernet"
  - "WLAN + Bluetooth"
  - "WWAN"
  - "Case Material"
  - "Bundled Accessories"
  - "Camera"
  - "Microphone"
  - "Color"
  - "Keyboard"
  - "Fingerprint Reader"
  - "NFC"
  - "TPM"
  - "Battery"
  - "Power Adapter"
  - "Operating System"
  - "Bundled Software"
  - "Base Warranty"
  - "Bundled Service"
  - "EAN / UPC / JAN"
  - "End of Support"
  - "Announce Date"
